# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birday',
            field=models.DateField(default='1991-1-1', verbose_name='\u751f\u65e5'),
        ),
    ]
