# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lesson_learn_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseresource',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u8bfe\u4ef6\u540d'),
        ),
    ]
