# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-02 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20170902_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='youneed_konw',
            new_name='need_konw',
        ),
    ]
